create database Loja_informatica;
use Loja_informatica;

create table carregador(cod_cr int not null auto_increment, nome_cr varchar(30) not null, modelo_cr varchar(30) not null, potencia_cr varchar(30), valor_cr int not null, primary key(cod_cr));
create table capinha(cod_cp int not null auto_increment, nome_cp varchar(30) not null, modelo_cp varchar(30) not null, cor_cp varchar(30) not null, valor_cp int not null, primary key(cod_cp));
create table pelicula(cod_pl int not null auto_increment, nome_pl varchar(30) not null, modelo_pl varchar(30) not null, tipo_pl varchar(30) not null, valor_pl int not null, primary key(cod_pl));
create table fone_cfio(cod_fc int not null auto_increment, nome_fc varchar(30) not null, cor_fc varchar(30) not null, valor_fc int not null, primary key(cod_fc));
create table fone_sfio(cod_fs int not null auto_increment, nome_fs varchar(30) not null, cor_fs varchar(30) not null, valor_fs int not null, primary key(cod_fs));
create table fonte_carregador(cod_fcr int not null auto_increment, nome_fcr varchar(30) not null, modelo_fcr varchar(30) not null, potencia_fcr varchar(30) not null, valor_fcr int not null, primary key(cod_fcr));
create table cabo(cod_cb int not null auto_increment, nome_cb varchar(30) not null, tipo_cb varchar(30) not null, cor_cb varchar(30) not null, tamanho_cb int not null, valor_cb int not null, primary key(cod_cb));
create table teclado(cod_tc int not null auto_increment, nome_tc varchar(30) not null, modelo_tc varchar(30) not null, cor_tc varchar(30) not null, valor_tc int not null, primary key(cod_tc));
create table mouse(cod_ms int not null auto_increment, nome_ms varchar(30) not null, modelo_ms varchar(30) not null, cor_ms varchar(30) not null, valor_ms int not null, primary key(cod_ms));
create table controle(cod_ct int not null auto_increment, nome_ct varchar(30) not null, modelo_ct varchar(30) not null, cor_ct varchar(30) not null, valor_ct int not null, primary key(cod_ct));

insert carregador values(null, 'samsung', 'tipo c', 'turbo', 40);
insert carregador values(null, 'samsung', 'tipo v8', 'normal', 30);
insert carregador values(null, 'motorola', 'tipo c', 'turbo', 40);
insert carregador values(null, 'motorola', 'tipo v8', 'normal', 30);
insert carregador values(null, 'iphone', 'tipo pl', 'turbo', 50);
insert carregador values(null, 'iphone', 'tipo c', 'turbo', 40);
insert carregador values(null, 'positivo', 'tipo c', 'turbo', 20);
insert carregador values(null, 'positivo', 'tipo v8', 'normal', 10);
insert carregador values(null, 'xaiomi', 'tipo c', 'turbo', 40);
insert carregador values(null, 'xaiomi', 'tipo v8', 'turbo', 30);
select * from carregador;

insert capinha values(null, 'samsung', 'a32', 'transparente', 50);
insert capinha values(null, 'samsung', 'a22', 'vermelho', 40);
insert capinha values(null, 'samsung', 'a71', 'preto', 30);
insert capinha values(null, 'motorola', 'g10', 'transparente', 50);
insert capinha values(null, 'motorola', 'g20', 'vermelho', 40);
insert capinha values(null, 'motorola', 'e31', 'preto', 30);
insert capinha values(null, 'iphone', '11', 'transparente', 50);
insert capinha values(null, 'iphone', '13', 'preto', 40);
insert capinha values(null, 'iphone', '13 max', 'azul', 30);
insert capinha values(null, 'xiaomi', 'note 8', 'transparente', 50);
insert capinha values(null, 'xiaomi', 'note 9', 'verde', 40);
insert capinha values(null, 'xiaomi', 'note 10', 'amarelo', 30);
select * from capinha;

insert pelicula values(null, 'samsung', 'a32', 'privacidade', 30);
insert pelicula values(null, 'samsung', 'a22', '3d', 20);
insert pelicula values(null, 'samsung', 'a71', 'normal', 10);
insert pelicula values(null, 'motorola', 'g10', 'privacidade', 30);
insert pelicula values(null, 'motorola', 'g20', '3d', 20);
insert pelicula values(null, 'motorola', 'g30', 'normal', 10);
insert pelicula values(null, 'iphone', '11', 'privacidade', 30);
insert pelicula values(null, 'iphone', '12', '3d', 20);
insert pelicula values(null, 'iphone', '13max', 'normal', 10);
insert pelicula values(null, 'xiaomi', 'note 8', 'privacidade', 30);
insert pelicula values(null, 'xiaomi', 'note 9', '3d', 20);
insert pelicula values(null, 'xiaomi', 'note 10', 'normal', 10);
select * from pelicula;

insert fone_cfio values(null, 'samsung x', 'preto', 100);
insert fone_cfio values(null, 'samsung xi', 'branco', 200);
insert fone_cfio values(null, 'motorola 8', 'preto', 100);
insert fone_cfio values(null, 'motorola pro', 'branco', 200);
insert fone_cfio values(null, 'redeset', 'preto', 100);
insert fone_cfio values(null, 'xiaomi 3', 'branco', 200);
insert fone_cfio values(null, 'iphonene', 'preto', 100);
insert fone_cfio values(null, 'jbl pro', 'branco', 200);
insert fone_cfio values(null, 'jbl nine', 'preto', 100);
insert fone_cfio values(null, 'jbl eit', 'branco', 200);
select * from fone_cfio;

insert fone_sfio values(null, 'samsung', 'preto', 100);
insert fone_sfio values(null, 'samsung 32', 'branco', 200);
insert fone_sfio values(null, 'motorola', 'preto', 100);
insert fone_sfio values(null, 'motorola max', 'branco', 200);
insert fone_sfio values(null, 'redeset nine', 'preto', 100);
insert fone_sfio values(null, 'xiaomi 2', 'branco', 200);
insert fone_sfio values(null, 'xiaomi 11', 'preto', 100);
insert fone_sfio values(null, 'jbl max', 'branco', 200);
insert fone_sfio values(null, 'jbl', 'preto', 100);
insert fone_sfio values(null, 'jbl turb', 'branco', 200);
select * from fone_sfio;

insert fonte_carregador values(null, 'samsung', 'entrada c', 'turbo', 40);
insert fonte_carregador values(null, 'samsung', 'entrada ubs', 'normal', 30);
insert fonte_carregador values(null, 'motorola', 'entrada c', 'turbo', 40);
insert fonte_carregador values(null, 'motorola', 'entrada usb', 'normal', 30);
insert fonte_carregador values(null, 'iphone', 'entrada c', 'turbo', 50);
insert fonte_carregador values(null, 'iphone', 'entrada ubs', 'turbo', 40);
insert fonte_carregador values(null, 'positivo', 'entrada c', 'turbo', 20);
insert fonte_carregador values(null, 'positivo', 'entrada ubs', 'normal', 10);
insert fonte_carregador values(null, 'xaiomi', 'entrada c', 'turbo', 40);
insert fonte_carregador values(null, 'xaiomi', 'entrada ubs', 'turbo', 30);
select * from fonte_carregador;

insert cabo values(null, 'samsung', 'tipo c', 'preto', 2, 40);
insert cabo values(null, 'samsung', 'tipo v8', 'branco', 1, 30);
insert cabo values(null, 'motorola', 'tipo c', 'azul', 3, 40);
insert cabo values(null, 'motorola', 'tipo v8', 'verde', 1, 30);
insert cabo values(null, 'iphone', 'tipo c', 'amarelo', 2, 50);
insert cabo values(null, 'iphone', 'tipo pl', 'vermelho', 3, 40);
insert cabo values(null, 'positivo', 'tipo c', 'marom', 1, 20);
insert cabo values(null, 'positivo', 'tipo v8', 'laranja', 2, 10);
insert cabo values(null, 'xaiomi', 'tipo c', 'branco', 3, 40);
insert cabo values(null, 'xaiomi', 'tipo v8', 'cinza', 1, 30);
select * from cabo;

insert teclado values(null, 'mecanike', 'com cabo', 'preto', 200);
insert teclado values(null, 'mecanike', 'sem cabo', 'branco', 300);
insert teclado values(null, 'hydra', 'com cabo', 'azul', 400);
insert teclado values(null, 'hydra', 'sem cabo', 'verde', 300);
insert teclado values(null, 'rise', 'com cabo', 'amarelo', 500);
insert teclado values(null, 'rise', 'sem cabo', 'vermelho', 400);
insert teclado values(null, 'hayom', 'com cabo', 'marom', 200);
insert teclado values(null, 'hayom', 'sem cabo', 'laranja', 100);
insert teclado values(null, 'gamer', 'com cabo', 'branco', 400);
insert teclado values(null, 'gamer', 'sem cabo', 'cinza', 300);
select * from teclado;

insert mouse values(null, 'mecanike', 'com cabo', 'preto', 20);
insert mouse values(null, 'mecanike', 'sem cabo', 'branco', 30);
insert mouse values(null, 'hydra', 'com cabo', 'azul', 40);
insert mouse values(null, 'hydra', 'sem cabo', 'verde', 30);
insert mouse values(null, 'rise', 'com cabo', 'amarelo', 50);
insert mouse values(null, 'rise', 'sem cabo', 'vermelho', 40);
insert mouse values(null, 'hayom', 'com cabo', 'marom', 20);
insert mouse values(null, 'hayom', 'sem cabo', 'laranja', 10);
insert mouse values(null, 'gamer', 'com cabo', 'branco', 40);
insert mouse values(null, 'gamer', 'sem cabo', 'cinza', 30);
select * from mouse;

insert controle values(null, 'ps2', 'com cabo', 'preto', 20);
insert controle values(null, 'ps', 'sem cabo', 'branco', 30);
insert controle values(null, 'ps4', 'com cabo', 'azul', 40);
insert controle values(null, 'ps5', 'sem cabo', 'verde', 30);
insert controle values(null, 'xbox 360', 'com cabo', 'amarelo', 50);
insert controle values(null, 'xbox one', 'sem cabo', 'vermelho', 40);
insert controle values(null, 'nitendo', 'com cabo', 'marom', 20);
insert controle values(null, 'switch', 'sem cabo', 'laranja', 10);
insert controle values(null, 'gamer box', 'com cabo', 'branco', 40);
insert controle values(null, 'xbox', 'sem cabo', 'cinza', 30);
select * from controle;